### ISSUE TITLE
Update to latest JOSM

### ISSUE THREAD

**Issue by don-vip** [kendzi/TombPlugin#19]
We have removed a lot of deprecated API as advertised on the mailing list, see https://josm.openstreetmap.de/ticket/15310

As a result this plugin is no longer compatible, can you please update it?

Thanks.

**Comment by kendzi** [comment]
fixed

**Comment by don-vip** [comment]
Thank you! Unfortunately a call to Main.worker was missed, see #20

**Comment by kendzi** [comment]
relised
